package com._98elements.springevents;

public enum ListenerType {
  // custom events
  WITH_SPEL_SPECIAL_CONDITION,
  WITH_ACCEPT_AND_REJECT_EVENT_TYPES,
  WITH_ACCEPT_EVENT_TYPE,

  // transactional events
  NON_TRANSACTIONAL,
  TRANSACTIONAL,
  TRANSACTIONAL_WITH_FALLBACK_EXECUTION,
  TRANSACTIONAL_SET_ONLY_AFTER_ROLLBACK,

  // generic events
  GENERIC_INVITATION_CREATED,
  GENERIC_PERSON_CREATED,
}
