package com._98elements.springevents;

public enum ListenerType {
  // custom events
  WITH_SPEL_SPECIAL_CONDITION,
  WITH_ACCEPT_AND_REJECT_EVENT_TYPES,
  WITH_ACCEPT_EVENT_TYPE,

  // transactional events
  NON_TRANSACTIONAL_LISTENER,
  TRANSACTIONAL_LISTENER,
  TRANSACTIONAL_LISTENER_WITH_FALLBACK_EXECUTION, TRANSACTIONAL_LISTENER_ONLY_AFTER_ROLLBACK,

  // standard events
  CONTEXT_REFRESHED_EVENT,
}
